# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4dc23bee28bc628d7bb69abda6315184172367367c6fcc1142cd6da9557d9a9788b35d70eb0fac176627b1da74dde423ae16c47775c475531152064db85680a

test:
  secret_key_base: 0787decfbfb2b04c37c6a54edd345e2eedc8e79f78604a463825e9092688f45b3d7d72d0e44c7b7a13a0488536df0a342d7a7a217046a91bfc1e5fb67444ddb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
